### ISSUE TITLE
Set up turret limits in WC

### ISSUE THREAD

**Issue by Blaylock1988** [Blaylock1988/GVK-AlphaKharak-Settings#1]

**Comment by Blaylock1988** [comment]
Set in WC, need to do total limits in BL

**Comment by Blaylock1988** [comment]
1. Grid PCU is 20 max because no plugin differentiates between them
2. Large grid weapons will have a built in WC cap of 20/PCU each
3. Small grid weapons will have a built in WC cap of 10/PCU each
4. Extra BL limits for max of 10 0-tech weapons (cumulative) on any grid

**Comment by Blaylock1988** [comment]
Mods updated, and BL set up but need to test. If BL does not work right then I can switch to JTurps Block Restrictions mod instead.

**Comment by AlphaMatte** [comment]
Large grid WC cap of 20 PCU confirmed

Small grid WC cap of 10PCU confirmed

BL cap of 10 0-tech weapons confirmed

**Comment by AlphaMatte** [comment]
Plugin/WC allows grids to connect and go over PCU but denies grids merging when over PCU - which is what we wanted.

**Comment by Blaylock1988** [comment]
Did you encounter any crashes like Rosy did?

**Comment by Blaylock1988** [comment]
Working as desired now
